"""Guardrails for the agent layer.

This module ensures that:
1. PII is masked before any data reaches the LLM
2. Agent outputs don't contain sensitive information
3. SQL injection patterns are blocked
4. Low-confidence responses trigger explicit fallbacks

LGPD compliance is not optional — it's enforced at the code level.
"""

import re
from dataclasses import dataclass

import structlog
import yaml

from src.exceptions import GuardrailViolationError, PIILeakageError

logger = structlog.get_logger()

# Regex patterns for Brazilian PII
CPF_PATTERN = re.compile(r"\d{3}\.?\d{3}\.?\d{3}-?\d{2}")
EMAIL_PATTERN = re.compile(r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}")
PHONE_PATTERN = re.compile(r"\(?\d{2}\)?\s?\d{4,5}-?\d{4}")
# Name detection is harder — we rely on column-level masking, not regex


@dataclass
class GuardrailConfig:
    """Configuration for guardrails loaded from YAML."""

    pii_fields: list[str]
    pii_mask_token: str
    max_sql_rows: int
    confidence_threshold: float
    fallback_response: str
    blocked_patterns: list[str]


def load_guardrail_config(
    config_path: str = "configs/agents.yaml",
) -> GuardrailConfig:
    """Load guardrail configuration from agents YAML."""
    with open(config_path) as f:
        raw = yaml.safe_load(f)

    gc = raw["guardrails"]
    return GuardrailConfig(
        pii_fields=gc["pii_fields"],
        pii_mask_token=gc["pii_mask_token"],
        max_sql_rows=gc["max_sql_rows"],
        confidence_threshold=gc["confidence_threshold"],
        fallback_response=gc["fallback_response"],
        blocked_patterns=gc["blocked_patterns"],
    )


def mask_pii_in_text(text: str, mask_token: str = "[REDACTED]") -> str:
    """Remove PII patterns from free text before sending to LLM.

    This is a defense-in-depth measure. The primary protection is
    column-level masking in the SQL tool (never SELECT name, cpf, email).
    This function catches any PII that leaks through.

    Args:
        text: Raw text that may contain PII.
        mask_token: Replacement string for detected PII.

    Returns:
        Text with PII patterns replaced.
    """
    masked = CPF_PATTERN.sub(mask_token, text)
    masked = EMAIL_PATTERN.sub(mask_token, masked)
    masked = PHONE_PATTERN.sub(mask_token, masked)
    return masked


def mask_pii_in_dataframe(
    df: "pd.DataFrame",
    pii_columns: list[str],
    mask_token: str = "[REDACTED]",
) -> "pd.DataFrame":
    """Mask PII columns in a DataFrame before it reaches the agent.

    This is the primary PII protection. Called by every tool that returns
    member-level data. PII columns are replaced entirely — not partially
    masked, not hashed. The agent has no business seeing CPFs.

    Args:
        df: DataFrame potentially containing PII columns.
        pii_columns: List of column names to mask.
        mask_token: Replacement value.

    Returns:
        DataFrame with PII columns replaced.
    """
    df = df.copy()
    for col in pii_columns:
        if col in df.columns:
            df[col] = mask_token
            logger.info("pii_column_masked", column=col, rows=len(df))
    return df


def validate_sql_query(query: str, blocked_patterns: list[str]) -> str:
    """Validate that a generated SQL query doesn't contain dangerous patterns.

    The agent generates SQL through a tool. This function ensures the SQL
    is read-only and doesn't attempt mutations.

    Args:
        query: SQL query string generated by the agent.
        blocked_patterns: Regex patterns to block.

    Returns:
        The query if valid.

    Raises:
        GuardrailViolationError: If a blocked pattern is detected.
    """
    query_upper = query.upper().strip()

    for pattern in blocked_patterns:
        if re.search(pattern, query_upper):
            logger.warning(
                "sql_guardrail_blocked",
                pattern=pattern,
                query_preview=query[:100],
            )
            raise GuardrailViolationError(
                rule="sql_safety",
                details=f"Blocked SQL pattern detected: {pattern}",
            )

    # Additional check: query must start with SELECT or WITH
    if not (query_upper.startswith("SELECT") or query_upper.startswith("WITH")):
        raise GuardrailViolationError(
            rule="sql_readonly",
            details="Only SELECT and WITH (CTE) queries are allowed",
        )

    return query


def validate_agent_output(
    output: str,
    mask_token: str = "[REDACTED]",
) -> str:
    """Validate agent output before returning to the user.

    Final defense layer. Checks for PII that somehow survived all
    prior masking. If found, masks it and logs a critical warning.

    Args:
        output: The agent's response text.
        mask_token: Replacement for any detected PII.

    Returns:
        Validated (and possibly re-masked) output.

    Raises:
        PIILeakageError: If PII is detected (after masking, as a warning signal).
    """
    pii_found = []

    if CPF_PATTERN.search(output):
        pii_found.append("cpf")
    if EMAIL_PATTERN.search(output):
        pii_found.append("email")
    if PHONE_PATTERN.search(output):
        pii_found.append("phone")

    if pii_found:
        # Mask it immediately
        cleaned = mask_pii_in_text(output, mask_token)
        # Log critical warning — this should not happen if upstream masking works
        logger.critical(
            "pii_leakage_in_agent_output",
            pii_types=pii_found,
            output_preview=output[:200],
        )
        # We mask and return rather than raising, to avoid breaking the user experience.
        # But we log at CRITICAL level so the team investigates.
        return cleaned

    return output


def check_confidence(
    confidence: float,
    threshold: float,
    fallback_response: str,
) -> tuple[bool, str | None]:
    """Check if agent confidence meets the threshold.

    Below threshold, we return an explicit "I don't know" rather than
    a potentially wrong answer. This is better for trust than hallucinating.

    Args:
        confidence: Agent's self-reported confidence (0-1).
        threshold: Minimum confidence to return a substantive answer.
        fallback_response: Message to return if below threshold.

    Returns:
        Tuple of (is_confident, fallback_message_or_none).
    """
    if confidence < threshold:
        logger.info(
            "agent_low_confidence",
            confidence=confidence,
            threshold=threshold,
        )
        return False, fallback_response

    return True, None
